version: '3'
services:
 
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
    - ./data:/var/lib/rabbitmq/mnesia:rw
    - ./definitions.json:/opt/definitions.json:ro
    - ./rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro

  votingapi:
    container_name: votingapi
    build: ./
    depends_on:
      - rabbitmq
    ports:
      - "8080:8080"

  votingfront:
    container_name: votingfront
    build: ../ng-catsvdogs
    ports:
      - "4200:4200"

  flyway:
    image: boxfuse/flyway:5.2.1
    command: -url=jdbc:mysql://db -schemas=votingdb -user=root -password=password -connectRetries=60 repair migrate
    volumes:
      - ./flyway:/flyway/sql
    depends_on:
      - mysql-dev
  
  mysql-dev:
    image: mysql:8.0.2
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: votingdb
    ports:
      - "3306:3306"

  worker:
    container_name: worker
    build: ../worker-catsvdogs
    depends_on:
      - rabbitmq
    ports:
      - "8081:8080"

  resultsapi:
    container_name: resultsapi
    build: ../resultsApi-catsvdogs
    depends_on:
      - mysql-dev
      - flyway
    ports:
      - "3000:3000"